import { ArticleStatus } from '@prisma/client';

export function buildArticleRow(overrides: Record<string, unknown> = {}) {
  return {
    id: 'art-1',
    slug: 'test-story',
    section: 'human_stories' as const,
    path: '/stories/test-story',
    status: ArticleStatus.PUBLISHED,
    categoryBg: 'Category',
    categoryEn: null,
    titleBg: 'История',
    titleEn: 'Story',
    subtitleBg: '',
    subtitleEn: null,
    readTimeBg: '',
    readTimeEn: null,
    locationBg: '',
    locationEn: null,
    dateBg: '',
    dateEn: null,
    photoCreditBg: '',
    photoCreditEn: null,
    endLabelBg: 'Край',
    endLabelEn: null,
    speakerBg: null,
    speakerEn: null,
    audioDuration: null,
    videoUrl: null,
    body: [],
    featured: false,
    sponsored: false,
    sourced: false,
    sponsorName: null,
    behindStoryBg: '',
    behindStoryEn: null,
    seoTitleBg: null,
    seoTitleEn: null,
    seoDescriptionBg: null,
    seoDescriptionEn: null,
    translationStatus: 'PENDING' as const,
    translationError: null,
    sourceLang: null,
    narrationStatus: 'IDLE' as const,
    narrationError: null,
    embedding: null,
    embeddingUpdatedAt: null,
    authorId: null,
    heroMediaId: null,
    audioMediaId: null,
    videoMediaId: null,
    author: null,
    heroMedia: null,
    audioMedia: null,
    videoMedia: null,
    galleryItems: [],
    seriesEpisodes: [],
    articleTags: [],
    articleCategories: [],
    publishedAt: new Date('2026-08-01T00:00:00.000Z'),
    createdAt: new Date('2026-08-01T00:00:00.000Z'),
    updatedAt: new Date('2026-08-01T00:00:00.000Z'),
    ...overrides,
  };
}

export function buildProductRow(overrides: Record<string, unknown> = {}) {
  return {
    id: 'prod-1',
    slug: 'journal',
    titleBg: 'Списание',
    titleEn: 'Journal',
    descriptionBg: '',
    descriptionEn: null,
    priceCents: 1500,
    currency: 'eur',
    stock: 10,
    active: true,
    allowCod: true,
    estimatedArrivalMinDays: 3,
    estimatedArrivalMaxDays: 5,
    estimatedArrivalDayType: 'BUSINESS' as const,
    estimatedArrivalBg: '3–5 работни дни',
    estimatedArrivalEn: '3–5 business days',
    imageMediaId: null,
    imageMedia: null,
    galleryItems: [],
    createdAt: new Date('2026-08-01T00:00:00.000Z'),
    updatedAt: new Date('2026-08-01T00:00:00.000Z'),
    ...overrides,
  };
}
