-- AlterEnum
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'AUTHOR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'CONTRIBUTOR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SUBSCRIBER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SEO_EDITOR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SEO_MANAGER';
