import { ArticleSection } from '@prisma/client';
import {
  assertRedirectMapReady,
  buildLegacyRedirectMap,
  countNginxMapEntries,
  destinationPath,
  LEGACY_REDIRECT_RESERVED_SLUGS,
  recommendedMapHashMaxSize,
  renderNginxRedirectMap,
} from './nginx-legacy-redirects';

function article(
  overrides: Partial<{
    slug: string;
    path: string;
    section: ArticleSection;
  }> = {},
) {
  return {
    slug: 'village-life',
    path: '/stories/village-life',
    section: 'human_stories' as ArticleSection,
    ...overrides,
  };
}

describe('destinationPath', () => {
  it('prefers the stored path', () => {
    expect(
      destinationPath(
        article({ path: '/places/belogradchik', slug: 'x', section: 'places' }),
      ),
    ).toBe('/places/belogradchik');
  });

  it('maps featured and human_stories onto /stories when path is empty', () => {
    expect(
      destinationPath(article({ path: '', slug: 'maria', section: 'human_stories' })),
    ).toBe('/stories/maria');
    expect(
      destinationPath(article({ path: '', slug: 'feat', section: 'featured' })),
    ).toBe('/stories/feat');
  });

  it('uses the section prefix for other sections', () => {
    expect(
      destinationPath(article({ path: '', slug: 'kukeri', section: 'traditions' })),
    ).toBe('/traditions/kukeri');
  });
});

describe('buildLegacyRedirectMap', () => {
  it('emits /{slug} and /{slug}/ onto the journal path', () => {
    const map = buildLegacyRedirectMap([
      article({
        slug: 'dvizhenieto-kato-chast-ot-choveka-sportniat-psiholog-vladimir-novkov',
        path: '/stories/dvizhenieto-kato-chast-ot-choveka-sportniat-psiholog-vladimir-novkov',
        section: 'human_stories',
      }),
    ]);

    expect(map.lines).toEqual([
      '/dvizhenieto-kato-chast-ot-choveka-sportniat-psiholog-vladimir-novkov /stories/dvizhenieto-kato-chast-ot-choveka-sportniat-psiholog-vladimir-novkov;',
      '/dvizhenieto-kato-chast-ot-choveka-sportniat-psiholog-vladimir-novkov/ /stories/dvizhenieto-kato-chast-ot-choveka-sportniat-psiholog-vladimir-novkov;',
    ]);
  });

  it('skips reserved hub slugs so /stories is not redirected', () => {
    expect(LEGACY_REDIRECT_RESERVED_SLUGS.has('stories')).toBe(true);
    const map = buildLegacyRedirectMap([
      article({ slug: 'stories', path: '/places/stories', section: 'places' }),
    ]);
    expect(map.lines).toEqual([]);
    expect(map.skipped).toEqual([{ slug: 'stories', reason: 'reserved' }]);
  });

  it('drops colliding slugs instead of guessing a section', () => {
    const map = buildLegacyRedirectMap([
      article({ slug: 'belogradchik', path: '/places/belogradchik', section: 'places' }),
      article({
        slug: 'belogradchik',
        path: '/stories/belogradchik',
        section: 'human_stories',
      }),
    ]);
    expect(map.lines).toEqual([]);
    expect(map.skipped.every((row) => row.reason === 'collision')).toBe(true);
  });

  it('can omit trailing-slash aliases', () => {
    const map = buildLegacyRedirectMap([article()], { trailingSlash: false });
    expect(map.lines).toEqual(['/village-life /stories/village-life;']);
  });
});

describe('renderNginxRedirectMap', () => {
  it('writes a comment header plus map lines', () => {
    const rendered = renderNginxRedirectMap(
      buildLegacyRedirectMap([article()], { trailingSlash: false }),
      { articles: 1, generatedAt: '2026-09-16T00:00:00.000Z' },
    );
    expect(rendered).toContain(
      '# Generated by api/src/wordpress-import/generate-nginx-redirects.ts',
    );
    expect(rendered).toContain('# articles: 1');
    expect(rendered).toContain('/village-life /stories/village-life;');
    expect(rendered).toContain('/authors/ami-tola /authors/eva-ivanova;');
  });
});

describe('redirect map guards', () => {
  it('counts nginx map entries and sizes the hash table', () => {
    const rendered = renderNginxRedirectMap(
      buildLegacyRedirectMap([article()]),
      { articles: 1, generatedAt: '2026-09-16T00:00:00.000Z' },
    );
    // 4 author-alias lines + village-life (+ trailing slash)
    expect(countNginxMapEntries(rendered)).toBe(6);
    expect(recommendedMapHashMaxSize(4000)).toBe(8192);
    expect(recommendedMapHashMaxSize(100)).toBe(2048);
  });

  it('refuses an empty or shrunken map unless forced', () => {
    expect(() => assertRedirectMapReady(0, undefined)).toThrow('min 1');
    expect(() => assertRedirectMapReady(10, 100)).toThrow('refusing to shrink');
    expect(() => assertRedirectMapReady(10, 100, { force: true })).not.toThrow();
    expect(() =>
      assertRedirectMapReady(10, undefined, { minRedirects: 20 }),
    ).toThrow('min 20');
  });
});
